//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.15 at 04:58:56 PM COT 
//


package com.prototype.api.employee.common.model.soap;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="request" type="{http://localhost:10002/employees}employeeRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "request"
})
@XmlRootElement(name = "createEmployeeRequest")
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CreateEmployeeRequest {

    @XmlElement(required = true)
    protected com.prototype.api.employee.common.model.soap.EmployeeRequest request;

    /**
     * Gets the value of the request property.
     *
     * @return possible object is
     * {@link com.prototype.api.employee.common.model.soap.EmployeeRequest }
     */
    public com.prototype.api.employee.common.model.soap.EmployeeRequest getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     *
     * @param value allowed object is
     *              {@link com.prototype.api.employee.common.model.soap.EmployeeRequest }
     */
    public void setRequest(com.prototype.api.employee.common.model.soap.EmployeeRequest value) {
        this.request = value;
    }

}
